# ***1__ SETTING-UP THE ENVIROMENT***

In [ ]:
!pip install --force-reinstall "datasets==2.18.0" "fsspec==2023.9.2" --quiet

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.0/62.0 kB 2.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.9/89.9 kB 8.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.7/57.7 kB 5.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.4/72.4 kB 6.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 510.5/510.5 kB 26.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 173.4/173.4 kB 16.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 11.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 73.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 484.2/484.2 kB 31.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.4/16.4 MB 115.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.5/66.5 kB 6.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.3/42.3 MB 14.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

In [ ]:
import os
os.kill(os.getpid(), 9)

# ***SETTING UP THE ENVIROMENT***

In [ ]:
# Import necessary libraries for tokenization, model, and data handling
import numpy as np
import tensorflow as tf
from transformers import AutoTokenizer, TFAutoModelForSequenceClassification
from datasets import load_dataset, Dataset
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
print("Successfully imported all the Libraries")

Successfully imported all the Libraries


In [ ]:
!pip install numpy==1.26.4 --quiet
import os
os._exit(00)  # Force Colab to restart after downgrade


ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 2.2.3 which is incompatible.
cudf-cu12 25.2.1 requires pyarrow<20.0.0a0,>=14.0.0; platform_machine == "x86_64", but you have pyarrow 20.0.0 which is incompatible.
thinc 8.3.6 requires numpy<3.0.0,>=2.0.0, but you have numpy 1.26.4 which is incompatible.


In [ ]:
!pip install -q transformers datasets

# **1 __ Loading & Checking the IMDB Dataset**

In [ ]:
from datasets import load_dataset

# Load IMDB dataset
imdb = load_dataset("imdb")

# Show structure
print(imdb)

# Show sample
print("\nSample example:")
print(imdb['train'][0])


/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


Generating train split:   0%|          | 0/25000 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/25000 [00:00<?, ? examples/s]

Generating unsupervised split:   0%|          | 0/50000 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 25000
    })
    test: Dataset({
        features: ['text', 'label'],
        num_rows: 25000
    })
    unsupervised: Dataset({
        features: ['text', 'label'],
        num_rows: 50000
    })
})

Sample example:
{'text': 'I rented I AM CURIOUS-YELLOW from my video store because of all the controversy that surrounded it when it was first released in 1967. I also heard that at first it was seized by U.S. customs if it ever tried to enter this country, therefore being a fan of films considered "controversial" I really had to see this for myself.<br /><br />The plot is centered around a young Swedish drama student named Lena who wants to learn everything she can about life. In particular she wants to focus her attentions to making some sort of documentary on what the average Swede thought about certain political issues such as the Vietnam War and race issues in the United States. In between askin

# **2 __ Loading &  Mapping GoEmotions Emotions to Sentiments**

In [ ]:
from datasets import load_dataset

# Load the GoEmotions dataset
goemotions = load_dataset("go_emotions")

# Get label names
label_names = goemotions['train'].features['labels'].feature.names

# Define emotion to sentiment mapping
positive_emotions = {'admiration', 'amusement', 'approval', 'curiosity', 'excitement', 'gratitude', 'joy', 'love', 'optimism', 'pride', 'relief'}
negative_emotions = {'anger', 'annoyance', 'disgust', 'disapproval', 'embarrassment', 'fear', 'grief', 'nervousness', 'disappointment', 'remorse', 'sadness'}
neutral_emotions = {'neutral'}

# Map emotions to sentiment labels
def map_emotions(example):
    emotions = [label_names[l] for l in example['labels']]
    sentiment = None
    for emo in emotions:
        if emo in positive_emotions:
            sentiment = 2  # Positive
            break
        elif emo in negative_emotions:
            sentiment = 0  # Negative
            break
        elif emo in neutral_emotions:
            sentiment = 1  # Neutral
            break
    return {'sentiment_label': sentiment}

# Apply mapping
goemotions_labeled = goemotions['train'].map(map_emotions)

# Filter out entries without a sentiment label
goemotions_labeled = goemotions_labeled.filter(lambda x: x['sentiment_label'] is not None)


Generating train split:   0%|          | 0/43410 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/5426 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/5427 [00:00<?, ? examples/s]

Map:   0%|          | 0/43410 [00:00<?, ? examples/s]

Filter:   0%|          | 0/43410 [00:00<?, ? examples/s]

# **3 __ Tokenizing the GoEmotions dataset**

In [ ]:
from transformers import AutoTokenizer

# Load the tokenizer used in your model
tokenizer = AutoTokenizer.from_pretrained("cardiffnlp/twitter-roberta-base-sentiment")

# Define a function to tokenize the text
def tokenize_function(example):
    return tokenizer(example["text"],max_length=64, truncation=True, padding="max_length")

# Apply tokenization
tokenized_goemotions = goemotions_labeled.map(tokenize_function, batched=True)

# Rename 'sentiment_label' to 'labels' for training compatibility
if "labels" in tokenized_goemotions.column_names:
    tokenized_goemotions = tokenized_goemotions.remove_columns("labels")
if "sentiment_label" in tokenized_goemotions.column_names:
    tokenized_goemotions = tokenized_goemotions.rename_column("sentiment_label", "labels")

# Set the format for TensorFlow (or PyTorch)
tokenized_goemotions.set_format("tensorflow")  # or use "torch" if you're using PyTorch


config.json:   0%|          | 0.00/747 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/150 [00:00<?, ?B/s]

Map:   0%|          | 0/40123 [00:00<?, ? examples/s]

# **4 __ Tokenizing the IMDB dataset**

In [ ]:
from transformers import AutoTokenizer

# Load the tokenizer
tokenizer = AutoTokenizer.from_pretrained("cardiffnlp/twitter-roberta-base-sentiment")

# Define a function for tokenization
def tokenize_function(example):
    return tokenizer(example["text"],max_length=64, padding="max_length", truncation=True)

# Tokenize the IMDB dataset
tokenized_imdb = imdb.map(tokenize_function, batched=True)


Map:   0%|          | 0/25000 [00:00<?, ? examples/s]

# **5 __ Mapping IMDB Labels to Match GoEmotions Labels**

In [ ]:
# Check label names (optional, just for your understanding)
print(imdb["train"].features["label"])

# Rename label column to 'sentiment_label' for consistency
def rename_label(example):
    return {"sentiment_label": example["label"]}

# Apply to tokenized IMDB
tokenized_imdb = tokenized_imdb.map(rename_label)


ClassLabel(names=['neg', 'pos'], id=None)


Map:   0%|          | 0/25000 [00:00<?, ? examples/s]

Map:   0%|          | 0/25000 [00:00<?, ? examples/s]

Map:   0%|          | 0/50000 [00:00<?, ? examples/s]

# **6 __ Aligning and Combining Both Datasets**

In [ ]:
from datasets import concatenate_datasets

# Use only the training split from IMDB
tokenized_imdb_train = tokenized_imdb["train"]

# Combine the tokenized datasets
combined_dataset = concatenate_datasets([tokenized_goemotions, tokenized_imdb_train])

# Shuffle the combined dataset
combined_dataset = combined_dataset.shuffle(seed=42)

# Set format for TensorFlow
combined_dataset.set_format("tensorflow")


# **7 __ Converting the Combined Dataset into TensorFlow-Compatible Tensors for Training**

In [ ]:
from datasets import Dataset, concatenate_datasets
from transformers import AutoTokenizer, DataCollatorWithPadding
import tensorflow as tf

# Fix label columns
if "sentiment_label" in tokenized_goemotions.column_names:
    tokenized_goemotions = tokenized_goemotions.rename_column("sentiment_label", "labels")
if "label" in tokenized_imdb["train"].column_names:
    tokenized_imdb = tokenized_imdb.rename_column("label", "labels")

# Drop None labels using pandas workaround
def drop_none_labels(dataset):
    df = dataset.to_pandas()  # <- FIX: use copy=True explicitly
    df = df[df["labels"].notnull()]
    df["labels"] = df["labels"].astype(int)
    return Dataset.from_pandas(df)

tokenized_goemotions = drop_none_labels(tokenized_goemotions)
tokenized_imdb_train = drop_none_labels(tokenized_imdb["train"])

# Combine datasets
combined_dataset = concatenate_datasets([tokenized_goemotions, tokenized_imdb_train])
combined_dataset = combined_dataset.shuffle(seed=42)

# Keep only necessary columns
combined_dataset = combined_dataset.remove_columns(
    [col for col in combined_dataset.column_names if col not in ["input_ids", "attention_mask", "labels"]]
)

# Convert to TensorFlow-compatible dataset
tokenizer = AutoTokenizer.from_pretrained("cardiffnlp/twitter-roberta-base-sentiment")
data_collator = DataCollatorWithPadding(tokenizer=tokenizer, return_tensors="tf")

tf_dataset = combined_dataset.to_tf_dataset(
    columns=["input_ids", "attention_mask"],
    label_cols="labels",
    shuffle=True,
    batch_size=16,
    collate_fn=data_collator
)

# Preview batch
for batch in tf_dataset.take(1):
    print(batch)


({'input_ids': <tf.Tensor: shape=(16, 64), dtype=int64, numpy=
array([[    0,   133, 29754, ...,     1,     1,     1],
       [    0,  9178,   109, ...,     1,     1,     1],
       [    0,   510, 39890, ...,     1,     1,     1],
       ...,
       [    0,   100,  1690, ...,     1,     1,     1],
       [    0, 37038, 26504, ...,     1,     1,     1],
       [    0, 10993,     9, ...,    18,    73,     2]])>, 'attention_mask': <tf.Tensor: shape=(16, 64), dtype=int64, numpy=
array([[1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       ...,
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 1, 1, 1]])>}, <tf.Tensor: shape=(16,), dtype=int64, numpy=array([1, 2, 2, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 2, 2, 1])>)


# **8 __ Defining and Compiling the Model**

In [ ]:
from transformers import TFAutoModelForSequenceClassification
import tensorflow as tf
from tf_keras.optimizers import Adam  # Use tf_keras, NOT tf.keras

# Load the model
model = TFAutoModelForSequenceClassification.from_pretrained(
    "cardiffnlp/twitter-roberta-base-sentiment",
    num_labels=3
)

# Define optimizer from tf_keras
optimizer = Adam(learning_rate=5e-5)

# Compile the model
model.compile(
    optimizer=optimizer,
    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    metrics=["accuracy"]
)


Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`


tf_model.h5:   0%|          | 0.00/501M [00:00<?, ?B/s]

All model checkpoint layers were used when initializing TFRobertaForSequenceClassification.

All the layers of TFRobertaForSequenceClassification were initialized from the model checkpoint at cardiffnlp/twitter-roberta-base-sentiment.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFRobertaForSequenceClassification for predictions without further training.


# **9 __ Training the Model**

In [ ]:
# Convert to TensorFlow-compatible dataset
tokenizer = AutoTokenizer.from_pretrained("cardiffnlp/twitter-roberta-base-sentiment")
data_collator = DataCollatorWithPadding(tokenizer=tokenizer, return_tensors="tf")

tf_dataset = combined_dataset.to_tf_dataset(
    columns=["input_ids", "attention_mask"],
    label_cols="labels",
    shuffle=True,
    batch_size=16, # The batching is already handled here
    collate_fn=data_collator
)

# Preview batch
for batch in tf_dataset.take(1):
    print(batch)

({'input_ids': <tf.Tensor: shape=(16, 64), dtype=int64, numpy=
array([[    0,   713,  2170, ...,     1,     1,     1],
       [    0,   487,  4668, ...,     1,     1,     1],
       [    0,  5733,  3829, ...,     1,     1,     1],
       ...,
       [    0, 10643,   768, ...,     1,     1,     1],
       [    0,   243,    17, ...,     1,     1,     1],
       [    0, 20369,  9382, ...,    22, 33601,     2]])>, 'attention_mask': <tf.Tensor: shape=(16, 64), dtype=int64, numpy=
array([[1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       ...,
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 1, 1, 1]])>}, <tf.Tensor: shape=(16,), dtype=int64, numpy=array([2, 1, 1, 1, 1, 2, 0, 1, 2, 1, 2, 1, 0, 2, 0, 0])>)


In [ ]:
# Train the model
history = model.fit(tf_dataset, epochs=3)

print("\n✅ Training Completed Successfully")

Epoch 1/3
4071/4071 [==============================] - 970s 225ms/step - loss: 0.5759 - accuracy: 0.7486
Epoch 2/3
4071/4071 [==============================] - 914s 224ms/step - loss: 0.4658 - accuracy: 0.8030
Epoch 3/3
4071/4071 [==============================] - 911s 224ms/step - loss: 0.3776 - accuracy: 0.8444

✅ Training Completed Successfully


# ***10 __ Evaluating the Model***

In [ ]:
loss, accuracy = model.evaluate(tf_dataset)
print(f"\n📊 Test Loss: {loss:.4f}")
print(f"✅ Test Accuracy: {accuracy:.4f}")


4071/4071 [==============================] - 329s 79ms/step - loss: 0.2372 - accuracy: 0.9129

📊 Test Loss: 0.2372
✅ Test Accuracy: 0.9129


# ***11 __ Making Predictions***

In [ ]:
import numpy as np

# Get model predictions
predictions = model.predict(tf_dataset).logits
predicted_labels = np.argmax(predictions, axis=1)

# Extract true labels from the test dataset
true_labels = np.concatenate([y for x, y in tf_dataset], axis=0)

# Print classification report
from sklearn.metrics import classification_report
print(classification_report(true_labels, predicted_labels, target_names=['negative', 'neutral', 'positive']))


4071/4071 [==============================] - 323s 79ms/step
              precision    recall  f1-score   support

    negative       0.34      0.34      0.34     21819
     neutral       0.39      0.38      0.39     25591
    positive       0.27      0.28      0.28     17713

    accuracy                           0.34     65123
   macro avg       0.33      0.33      0.33     65123
weighted avg       0.34      0.34      0.34     65123



# ***12 __ Saving the Model***

In [ ]:
# Save the model
model.save_pretrained("sentiment_model")

# Save the tokenizer
tokenizer.save_pretrained("sentiment_model")


('sentiment_model/tokenizer_config.json',
 'sentiment_model/special_tokens_map.json',
 'sentiment_model/vocab.json',
 'sentiment_model/merges.txt',
 'sentiment_model/added_tokens.json',
 'sentiment_model/tokenizer.json')

# ***13 __ Predictions for own Data***

In [ ]:
def predict_sentiment(text):
    inputs = tokenizer(text, return_tensors="tf", truncation=True, padding=True, max_length=64)
    outputs = model(inputs)
    probs = tf.nn.softmax(outputs.logits, axis=1)
    prediction = tf.argmax(probs, axis=1).numpy()[0]

    label_map = {0: "negative", 1: "neutral", 2: "positive"}
    confidence = np.max(probs.numpy())

    result = f"Tweet: {text}\n{label_map[prediction].capitalize()} (Confidence: {confidence:.2f})\n"
    return result


In [ ]:
tweet1 = "The product arrived as expected.",
tweet2 = " nothing  special here .",
tweet3 = " i have neutral feelings for this movie"

print(predict_sentiment(tweet1))
print(predict_sentiment(tweet2))
print(predict_sentiment(tweet3))


Tweet: ('The product arrived as expected.',)
Neutral (Confidence: 0.57)

Tweet: (' nothing  special here .',)
Neutral (Confidence: 0.56)

Tweet:  i have neutral feelings for this movie
Neutral (Confidence: 0.88)

